tasks:
  - name: cors-host-config
    before: bash hostURL.sh
    command: gp open README.md
  - name: graphQL-Client
    before: |
      cd graphql-client-examples
      nvm install 16.13.0
      npm install -g npm@latest
      npm install astra-setup
      npm install -g netlify-cli
      npm install
      # astra-cli
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli-java" | bash >> ./install.log
    command: |
      source /home/gitpod/.astra/cli/astra-init.sh
      clear
      echo -e "\n*** workshop-intro-to-graphql gitpod ready - LET'S DO THIS! ***\n"
  - name: graphQL-Backend
    openMode: split-right
    init: |
      # REMOVE USER VALIDATION -Y ON JAVA 17 INSTALLATION
      sed -i '1,$s/sdkman_auto_answer=false/sdkman_auto_answer=true/' /home/gitpod/.sdkman/etc/config 
      sed -i '1,$s/sdkman_selfupdate_enable=true/sdkman_selfupdate_enable=false/' /home/gitpod/.sdkman/etc/config 
      # JAVA17 INSTALL
      sdk install java
    before: |
      cd graphql-backend-examples
      mvn clean install
    command: |
      # astra-cli
      unset JAVA_TOOL_OPTIONS
      source /home/gitpod/.astra/cli/astra-init.sh
      #
      cd graphql-backend-examples
      mvn spring-boot:run
ports:
  - port: 8888
    onOpen: open-preview
  - port: 8080
    visibility: public
    onOpen: open-browser
  - port: 3000
    onOpen: ignore      
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
